### PR TITLE
Downgrade onnx from 1.16.2 to 1.16.1 

### PR DESCRIPTION
**Pull request by pinnintipraneethkumar**
- ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed. 

- Observe this behaviour in windows11 the rootcause is onnx version downgrade to onnx==1.16.1 fix this issue.

### CODE REVIEW

**Comment by vietanhdev** [comment]
Hi @pinnintipraneethkumar,
Thank you for your contribution. Could you update the versions in `requirements-macos.txt` and `setup.py` too?

**Comment by pinnintipraneethkumar** [comment]
Sure!, I will update

Thank you.

**Comment by pinnintipraneethkumar** [comment]
Hi @vietanhdev,

I have updated the setup.py and macos.txt , Thank you

**Review by vietanhdev — APPROVED** [review]
Thank you! 👍

**Pull request merged**
