### PR TITLE
All yolov5 models are supported

### PR DESCRIPTION
**Pull request by hdnh2006**
Hello, 

This PR allows all yolov5 models supported but the problem is the models are taken from my forked [repo](https://github.com/hdnh2006/anylabeling-assets/releases/tag/v0.0.0). Could you please add all these assets to your repo or [this](https://github.com/vietanhdev/anylabeling/releases/tag/v0.1.1) tag? So the models will be downloaded from it.

On the other hand, I don't understand why the home directory is not the workspace folder, so I changed this
```
home_dir = os.path.expanduser("~")
``` 

to this:
```
home_dir = os.getcwd()
```
in the `model.py` file. Please let me know what should I do here in the PR review.

Thanks

### CODE REVIEW

**Comment by hdnh2006** [comment]
Ok, could you please upload the onnx files for the other yolov5 models as I suggested? So I can continue developing for yolov8 models and new functionalities.

**Comment by vietanhdev** [comment]
On the way...
Could you send me the models for YOLOv8 also?

**Comment by vietanhdev** [comment]
Please use the models here: https://github.com/vietanhdev/anylabeling-assets/releases/tag/v0.0.1

**Comment by hdnh2006** [comment]
Ok, I'll do it as soon as I can

**Comment by hdnh2006** [comment]
Hello again @vietanhdev, now all the models are downloaded from your repo (https://github.com/vietanhdev/anylabeling-assets/releases/tag/v0.0.1) and all yolov5 models are supported. I have also added GPU support for segment anything. 

Please check, and let me know if you request for any changes.

**Comment by hdnh2006** [comment]
I close this PR due to YOLOv8 now is supported on my repo

**Pull request closed without merging**
